
#
# This LookML file was generated by AtScale on 2025-10-23T16:10:18.562509876Z
#
# AtScale version: 2025.6.2
# Catalog: adventure-small-sml_main

connection: "trumid12109conn"
label: "adventure-small-sml_main"


include: "/views/adventure-small-sml_main/ASAdventureSmall.view.lkml"

include: "/views/adventure-small-sml_main/ResellerPerspective.view.lkml"


explore: ASAdventureSmall {
  label: "ASAdventureSmall"
}

explore: ResellerPerspective {
  label: "ResellerPerspective"
}

