
#
# This LookML file was generated by AtScale on 2025-10-08T15:07:47.442427895Z
#
# AtScale version: C2025.10.0
# Catalog: trumid_atscale.catalog_main

connection: "trumid12109conn"
label: "trumid_atscale.catalog_main"


include: "/views/trumid_atscale.catalog_main/rates.view.lkml"

include: "/views/trumid_atscale.catalog_main/rfq.view.lkml"


explore: rates {
  label: "rates"
}

explore: rfq {
  label: "rfq"
}

